export { getContactsQuantity } from './getContactsQuantity';
export { getGroupsQuantity } from './getGroupsQuantity';
export { renderIcons } from './renderIcons';
export { getCurrentTime } from './getCurrentTime';
export { getRandomColors } from './getRandomColors';
export { getModalMessage } from './getModalMessage';
export { makeSlug } from './makeSlug';
export { removeExtraWhitespace } from './removeExtraWhitespace';
export { convertHyphenatedString } from './convertHyphenatedString';
export { isExistByName, isExistByNumber } from './checkContactExistence';
export * as Notifications from './notifications';
